version: '2'

services:

    nginx-proxy:
        image: jwilder/nginx-proxy
        container_name: nginx-proxy
        restart: always
        ports:
            - 80:80
            - 443:443
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
            - ./certs/:/etc/nginx/certs/

    dnsmasq:
        image: andyshinn/dnsmasq
        container_name: dnsmasq
        restart: always
        depends_on:
            - nginx-proxy
        entrypoint:
            - dnsmasq
            - -k
            - --address=/.devel/127.0.0.1
        cap_add:
            - NET_ADMIN
        ports:
            - "53:53/tcp"
            - "53:53/udp"
